# Generated by Django 4.1.7 on 2023-04-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESS', 'Processing'), ('SHIP', 'Shipping'), ('DELIVERE', 'Delivered'), ('COMPLETE', 'Completed'), ('CANCEL', 'Canceled')], default='PENDING', max_length=9),
        ),
    ]
