# Generated by Django 4.1.7 on 2023-04-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='activation_code',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
